### ISSUE TITLE
Ignore unstable versions

### ISSUE THREAD

**Issue by jackrandom** [PicturePipe/renovate-config#1]
Renovate opens PR for updating to beta versions, i.e. https://github.com/PicturePipe/infrastructure/pull/108.

There is the possibility to configure [unstablePattern](https://renovatebot.com/docs/configuration-options/#unstablepattern). 

Looking at https://circleci.com/docs/2.0/docker-image-tags.json, I think it's a good idea to ignore images containing a {b, a, rc} or similiar, followed by a number, in their name. 

will do a PR for that.

**Comment by jackrandom** [comment]
I'm unsure if https://github.com/renovatebot/renovate/issues/3929 is valid. If it is, we'd have to use a different `packagePatterns` or at least set `recreateClosed` to false (default). I don't know why this should be true anyway.

**Comment by cfra** [comment]
My understanding is the following, it might not be completely correct though: `recreateClosed` needs to be set because there are often two docker images which need to be updated, e.g. `python` and `circleci/python`.

If there is an update for `python` to version `3.7.5`, renovate will open a PR. Let's say there is no update `3.7.5` for `circleci/python` yet.

The PR gets merged.

Now, there the update `3.7.5` for `circleci/python` is released. Renovate looks through the existing pull requests and realizes there is already a merged PR which updates `python` to `3.7.5`.

As there is already a merged PR, Renovate will not open a new PR to upgrade `circleci/python` with `recreateClosed` unset.
